### ISSUE TITLE
gunzip -k option ... -k not universal in all gzip/gunzip installations

### ISSUE THREAD

**Issue by MikeAxtell** [Gregor-Mendel-Institute/nanoPARE#1]
endMap.sh decompresses .gz compressed fastq files at line 213 with:
`gunzip -k -c $fastq_dir/$fastq_file > $sample_dir/"$sample_name"."$mate_number".fastq`

https://github.com/Gregor-Mendel-Institute/nanoPARE/blob/05b8f472c694a44ba5d67f061bf2faea873bb32e/endMap.sh#L213

... On my university's compute cluster, the version of gzip present does not have a -k option, so endMap.sh fails when inputing gzip-compressed fastq files. Our version of gzip/gunzip that lacks option '-k' is 
```
gzip --version
gzip 1.3.12
Copyright (C) 2007 Free Software Foundation, Inc.
Copyright (C) 1993 Jean-loup Gailly.
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

Written by Jean-loup Gailly.
```

**Comment by maschon0** [comment]
Writing to stdout with -c should have identical behavior with or without -k.
This was the only instance of gzip/gunzip -k I could find in the repo, so I've removed it in the current commit.

**Comment by MikeAxtell** [comment]
Thanks. I asked the admin of our cluster to update with a more modern version of gzip that includes -k as well.
