### ISSUE TITLE
Unable to run endMap.sh on provided sample data

### ISSUE THREAD

**Issue by MikeAxtell** [Gregor-Mendel-Institute/nanoPARE#2]
Trying to test with provided example data, but failing in a way I can't figure out. Successfully ran ./nanoPARE_setup.sh. Then tried to run endMap.sh as follows:
`./endMap.sh --cpus 2 --ram 10 -L 1`
All 'results' files are empty. Within the corresponding 'temp' directory I see:
`-rw-rw---- 1 mja18 mja18_collab  18M Apr 30 09:33 flower_1.1.fastq
-rw-rw---- 1 mja18 mja18_collab    0 Apr 30 09:33 flower_1.2.fastq
-rw-rw---- 1 mja18 mja18_collab    0 Apr 30 09:34 flower_1.5P.minus.bedgraph
-rw-rw---- 1 mja18 mja18_collab   19 Apr 30 09:34 flower_1_5P_minus_untemp.bedgraph
-rw-rw---- 1 mja18 mja18_collab    0 Apr 30 09:34 flower_1.5P.plus.bedgraph
-rw-rw---- 1 mja18 mja18_collab   19 Apr 30 09:34 flower_1_5P_plus_untemp.bedgraph
-rw-rw---- 1 mja18 mja18_collab    0 Apr 30 09:34 flower_1_cleaned.1.fastq
-rw-rw---- 1 mja18 mja18_collab 2.4K Apr 30 09:34 flower_1.sam
-rw-rw---- 1 mja18 mja18_collab  473 Apr 30 09:34 flower_1.star.log
-rw-rw---- 1 mja18 mja18_collab    0 Apr 30 09:34 flower_1.uG.minus.bedgraph
-rw-rw---- 1 mja18 mja18_collab    0 Apr 30 09:34 flower_1.uG.plus.bedgraph
-rw-rw---- 1 mja18 mja18_collab   17 Apr 30 09:34 length.table
drwxrws--- 4 mja18 mja18_collab 4.0K Apr 30 09:34 star
`
In particular I noticed that the 'flower_1_cleaned.1.fastq' file is empty. I believe this is the file fed to STAR.

A few error messages, from python, come through during the run:
`  File "/storage/home/mja18/work/nanoPARE/scripts/python_scripts/fastq_drop_short_reads.py", line 37
    print "Finished cleaning."
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finished cleaning.")?
`

than a few lines later:
`cat: flower_1_cleaned.fastq: No such file or directory`

Python version Python 3.6.3 :: Anaconda, Inc.

Any suggestions? I can send more details if you need them. Thanks in advance for your advice.

**Comment by maschon0** [comment]
This is caused by an earlier version of the pipeline being written for Python 2.7, and a couple of pre-final Python scripts snuck into the release version. I just pushed an update to the two Python scripts responsible for this issue and was able to run  `./endMap.sh --cpus 2 --ram 10 -L 1` on our cluster.  
Software versions for testing:  
--Python 3.6.6
--cutadapt 1.18 
--STAR 2.6.1c
--samtools 1.9
--bedtools 2.27.1

Does this fix the problem?

**Comment by MikeAxtell** [comment]
Great, thanks. Confirmed fixed.
