### ISSUE TITLE
setup failure with custom genome / STAR index fail?

### ISSUE THREAD

**Issue by MikeAxtell** [Gregor-Mendel-Institute/nanoPARE#6]
Hi again Michael, really sorry to keep posting things, but I think I have another bug (or anyway something I can't work through myself). First time I tried to run ./nanoPARE_setup.sh with my own genome rather than the test data, it looks like STAR indexing failed, and there are some python errors and other errors in the output. Here's my command:

`./nanoPARE_setup.sh -G cuscuta_campestris_assembly_r0-32.fasta -A combined_ccm.gff`

.. and I had modified in place the reference.table file to reflect my data instead of the test data. Here's a snipper showing the error messages. Any suggestions? Thanks again so much for your time.

> python /storage/home/mja18/work/nanoPARE/scripts/python_scripts/fasta_lengths.py cuscuta_campestris_assembly_r0-32.fasta > /storage/home/mja18/work/nanoPARE/resources/length.table
Traceback (most recent call last):
  File "/storage/home/mja18/work/nanoPARE/scripts/python_scripts/fasta_lengths.py", line 19, in <module>
    if line[0]=='>':
IndexError: string index out of range
Length table generated.
 Runtime error (func=(main), adr=3): Parameter number mismatch
./nanoPARE_setup.sh: line 94: [: -gt: unary operator expected
STAR --runThreadN 1 --runMode genomeGenerate --genomeDir /storage/home/mja18/work/nanoPARE/temp/genome_index --outFileNamePrefix /storage/home/mja18/work/nanoPARE/log/ --genomeFastaFiles cuscuta_campestris_assembly_r0-32.fasta --genomeSAindexNbases  --sjdbGTFfile combined_ccm.gff
EXITING: FATAL INPUT ERROR: empty value for parameter "genomeSAindexNbases" in input "Command-Line"
SOLUTION: use non-empty value for this parameter
May 02 10:47:40 ...... FATAL ERROR, exiting

**Comment by maschon0** [comment]
I appreciate your perseverance!  
From what I can see here, nanoPARE_setup.sh is failing to create the two-column table of chromosome/contig names and lengths from the provided FASTA file, apparently due to an empty line somewhere in the file. STAR crashes downstream because it requires an index length for its suffix array that is proportional to the genome size, and this index length is calculated by nanoPARE_setup.sh using the length.table that failed.  

I've pushed a fix to fasta_lengths.py to bypass empty lines, and you should be able to see the file resources/length.table that catalogs the size of the chromosomes in your genome file.

**Comment by MikeAxtell** [comment]
Thanks so much! That solved the issue. Yes it looks like the genome FASTA file I was working with has empty lines between each scaffold; that must have broken your parser.

**Comment by maschon0** [comment]
Good to know! It's probably worthwhile to mention here that the [FASTA format](https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastDocs&DOC_TYPE=BlastHelp) technically doesn't allow blank lines within the file, so I can't guarantee that third party software will handle your genome file appropriately.

**Comment by MikeAxtell** [comment]
Yup. I'm at the mercy of the people who made this darn genome assembly.

Thanks!
Mike


On Fri, May 3, 2019 at 3:51 AM Michael Schon <notifications@github.com>
wrote:

> Good to know! It's probably worthwhile to mention here that the FASTA
> format
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblast.ncbi.nlm.nih.gov%2FBlast.cgi%3FCMD%3DWeb%26PAGE_TYPE%3DBlastDocs%26DOC_TYPE%3DBlastHelp&data=02%7C01%7Cmja18%40psu.edu%7C47f8c0e3144748989ec508d6cf9c23b6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636924666870122854&sdata=Y9kGensYzPenNxFG0OhzvjtA3faxVhY0%2B0lRVLy9Rrg%3D&reserved=0>
> technically doesn't allow blank lines within the file, so I can't guarantee
> that third party software will handle your genome file appropriately.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGregor-Mendel-Institute%2FnanoPARE%2Fissues%2F6%23issuecomment-488991660&data=02%7C01%7Cmja18%40psu.edu%7C47f8c0e3144748989ec508d6cf9c23b6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636924666870122854&sdata=053hMOuiSl%2BwUcu0LP7smLzZwNXc3EnJItwdONLf698%3D&reserved=0>,
> or mute the thread
> <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABUJPCINH2THKEUWZSGIDCLPTPVHTANCNFSM4HJ7H46Q&data=02%7C01%7Cmja18%40psu.edu%7C47f8c0e3144748989ec508d6cf9c23b6%7C7cf48d453ddb4389a9c1c115526eb52e%7C0%7C0%7C636924666870132868&sdata=aLSy3P1qYe0cd0w3mpoITR7%2F4yJAm6FIs1kBKmEKf1M%3D&reserved=0>
> .
>


-- 
Michael J. Axtell, Ph.D.
Professor of Biology
The Pennsylvania State University
http://sites.psu.edu/axtell
http://plantsmallrnagenes.science.psu.edu
